version: '3.8'
services:
  apigateway:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8081:8080
    volumes:
      - ./app:/app
    extra_hosts:
      #"host.docker.internal" only works for Mac and Windows. In Linux, it is not able to connect
      #to the docker host from containers, we have to manually add extra_hosts for each container.
      #This step is not necessary for Mac and Windows.
      - "host.docker.internal:host-gateway"
